<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms> 
    <ImplicitUsings>disable</ImplicitUsings> 
    <ApplicationIcon>assets\curren_chan.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Update="assets\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>